### ISSUE TITLE
AFNetworking dependency

### ISSUE THREAD

**Issue by daliadanila** [deanWombourne/AFNetworking-streaming#3]
Hi,

Could the dependency be updated to a higher version? Version 2.3 can't be installed anymore.

Output when trying to install the pod: 

365Agiles-MacBook-Pro:Castleton.iOS.EDRM daliadanila$ pod install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 2.3)` required by `AFNetworking+streaming (0.1)`

Specs satisfying the `AFNetworking (~> 2.3)` dependency were found, but they required a higher minimum deployment target. 

Thanks

**Comment by deanWombourne** [comment]
Hey.

Sorry about the delay!

I've pushed two new releases to trunk - one is 0.6.3, this is the latest 2.x AFNetworking and I probably won't look at 2.x again (bugs notwithstanding).

I've also pushed up version 1.0, which ups the AFNetworking version to 3.0.

Let me know if this solves your issues :)

**Comment by deanWombourne** [comment]
Please ignore my last message - I decided to make the effort and I've made version 1.0.2 compatible with 2 and 3.

**Comment by daliadanila** [comment]
Hi Sam,

After running "pod update" it started to install the pod and now it seems to work fine.

Btw, this seems to be the only library for iOS that streams data so keep up the good work and thanks for the update!
